Imports BL
Imports System.Windows.Forms
Imports DevExpress.XtraGrid.Views.Grid
Public Class JobOrderShortClose
    Public FRMSTRING As String = ""

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub PurchaseOrderClose_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Then
                Me.Close()
            ElseIf e.KeyCode = Keys.Space And e.Control = True Then
                'SELECT ALL DATA
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CLOSED") = Not Convert.ToBoolean(dtrow("CLOSED"))
                Next
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub PurchaseOrderClose_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            Dim DTROW() As DataRow
            DTROW = USERRIGHTS.Select("FormName = 'SHORTCLOSE'")
            USERADD = DTROW(0).Item(1)
            USEREDIT = DTROW(0).Item(2)
            USERVIEW = DTROW(0).Item(3)
            USERDELETE = DTROW(0).Item(4)

            If USEREDIT = False And USERVIEW = False Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If
            fillgrid("")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid(ByVal TEMPCONDITION)
        Try
            Dim objclsCMST As New ClsCommonMaster
            Dim dt As New DataTable
            If FRMSTRING = "CLOSEPE" Then
                If RBPENDING.Checked = True Then
                    dt = objclsCMST.search("*", "", " (SELECT CAST (0 AS BIT) AS CLOSED,ISNULL(ALLJOBORDERFORPE.JO_NO, 0) AS JONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(COUNTRYMASTER.country_name, '') AS DESTINATION, ISNULL(ALLJOBORDERFORPE.JO_CIFOB, '') AS CIFFOB, ISNULL(CURRENCYMASTER.CURR_NAME, '') AS CURRENCY, ISNULL(ALLJOBORDERFORPE.JO_SHIPTOID, '') AS SHIPTO, ISNULL(ALLJOBORDERFORPE.JO_BANKDETAILS, '') AS BANKDETAILS, ISNULL(ALLJOBORDERFORPE.JO_REMARKS, '') AS REMARKS, ALLJOBORDERFORPE.JO_DATE AS DATE, ISNULL(ITEMMASTER.ITEM_NAME, '')  AS FINISHEDQUALITY, ISNULL(ALLJOBORDERFORPE_DESC.JO_GSM, '') AS GSM, ISNULL(ALLJOBORDERFORPE_DESC.JO_SIZE, 0) AS SIZE, ISNULL(ALLJOBORDERFORPE_DESC.JO_FOILQUALITYID, '') AS FOILQUALITY,  ISNULL(ALLJOBORDERFORPE_DESC.JO_FOILGSM, '') AS FOILGSM, ISNULL(ALLJOBORDERFORPE_DESC.JO_PEGSM, '') AS PEGSM, ISNULL(ALLJOBORDERFORPE_DESC.JO_ROLLDIEAMETER, '') AS ROLLDIAMETER, ISNULL(ALLJOBORDERFORPE_DESC.JO_COREPIPEWIDTH, '') AS COREPIPEWIDTH, ISNULL(ALLJOBORDERFORPE_DESC.JO_PALLETIZED, '') AS PALLETIZED, ISNULL(ALLJOBORDERFORPE_DESC.JO_NARRATION, '') AS NARRATION,  ROUND(ALLJOBORDERFORPE_DESC.JO_QTY - ALLJOBORDERFORPE_DESC.JO_READYQTY,0) AS QTY,  ISNULL(ALLJOBORDERFORPE_DESC.JO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(ALLJOBORDERFORPE_DESC.JO_DESC, '') AS GRIDDESC, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(PORTMASTER.PORT_name, '') AS PORTDISCHARGE, ISNULL(PORTMASTER_1.PORT_name, '') AS PORTLOADING,  ISNULL(ALLJOBORDERFORPE.JO_PROFORMANO, 0) AS PROFORMANO ,   ISNULL(ALLJOBORDERFORPE.TYPE, '') AS TYPE FROM COUNTRYMASTER RIGHT OUTER JOIN  ALLJOBORDERFORPE LEFT OUTER JOIN PORTMASTER AS PORTMASTER_1  ON ALLJOBORDERFORPE.JO_PORTLOADINGID = PORTMASTER_1.PORT_id  LEFT OUTER JOIN PORTMASTER ON ALLJOBORDERFORPE.JO_PORTDISCHARGEID = PORTMASTER.PORT_id LEFT OUTER JOIN  LEDGERS ON ALLJOBORDERFORPE.JO_LEDGERID = LEDGERS.Acc_id ON COUNTRYMASTER.country_id = ALLJOBORDERFORPE.JO_DESTINATIONID LEFT OUTER JOIN CURRENCYMASTER ON ALLJOBORDERFORPE.JO_CURRENCYID = CURRENCYMASTER.CURR_ID LEFT OUTER JOIN ITEMMASTER RIGHT OUTER JOIN ALLJOBORDERFORPE_DESC LEFT OUTER JOIN UNITMASTER ON ALLJOBORDERFORPE_DESC.JO_UNITID = UNITMASTER.unit_id ON ITEMMASTER.item_id = ALLJOBORDERFORPE_DESC.JO_QUALITYID ON ALLJOBORDERFORPE.JO_NO = ALLJOBORDERFORPE_DESC.JO_NO WHERE ALLJOBORDERFORPE_DESC.JO_CLOSED = 'FALSE' AND  ALLJOBORDERFORPE.JO_YEARID =  " & YearId & "  AND ROUND(ALLJOBORDERFORPE_DESC.JO_QTY - ALLJOBORDERFORPE_DESC.JO_READYQTY,0) > 0" & ") AS T ", " ORDER BY T.DATE, T.JONO, T.GRIDSRNO")
                Else
                    dt = objclsCMST.search("*", "", " (SELECT CAST (0 AS BIT) AS CLOSED,ISNULL(ALLJOBORDERFORPE.JO_NO, 0) AS JONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(COUNTRYMASTER.country_name, '') AS DESTINATION, ISNULL(ALLJOBORDERFORPE.JO_CIFOB, '') AS CIFFOB, ISNULL(CURRENCYMASTER.CURR_NAME, '') AS CURRENCY, ISNULL(ALLJOBORDERFORPE.JO_SHIPTOID, '') AS SHIPTO, ISNULL(ALLJOBORDERFORPE.JO_BANKDETAILS, '') AS BANKDETAILS, ISNULL(ALLJOBORDERFORPE.JO_REMARKS, '') AS REMARKS, ALLJOBORDERFORPE.JO_DATE AS DATE, ISNULL(ITEMMASTER.ITEM_NAME, '')  AS FINISHEDQUALITY, ISNULL(ALLJOBORDERFORPE_DESC.JO_GSM, '') AS GSM, ISNULL(ALLJOBORDERFORPE_DESC.JO_SIZE, 0) AS SIZE, ISNULL(ALLJOBORDERFORPE_DESC.JO_FOILQUALITYID, '') AS FOILQUALITY,  ISNULL(ALLJOBORDERFORPE_DESC.JO_FOILGSM, '') AS FOILGSM, ISNULL(ALLJOBORDERFORPE_DESC.JO_PEGSM, '') AS PEGSM, ISNULL(ALLJOBORDERFORPE_DESC.JO_ROLLDIEAMETER, '') AS ROLLDIAMETER, ISNULL(ALLJOBORDERFORPE_DESC.JO_COREPIPEWIDTH, '') AS COREPIPEWIDTH, ISNULL(ALLJOBORDERFORPE_DESC.JO_PALLETIZED, '') AS PALLETIZED, ISNULL(ALLJOBORDERFORPE_DESC.JO_NARRATION, '') AS NARRATION,  ROUND(ALLJOBORDERFORPE_DESC.JO_QTY - ALLJOBORDERFORPE_DESC.JO_READYQTY,0) AS QTY,  ISNULL(ALLJOBORDERFORPE_DESC.JO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(ALLJOBORDERFORPE_DESC.JO_DESC, '') AS GRIDDESC, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(PORTMASTER.PORT_name, '') AS PORTDISCHARGE, ISNULL(PORTMASTER_1.PORT_name, '') AS PORTLOADING,  ISNULL(ALLJOBORDERFORPE.JO_PROFORMANO, 0) AS PROFORMANO ,   ISNULL(ALLJOBORDERFORPE.TYPE, '') AS TYPE FROM COUNTRYMASTER RIGHT OUTER JOIN  ALLJOBORDERFORPE LEFT OUTER JOIN PORTMASTER AS PORTMASTER_1  ON ALLJOBORDERFORPE.JO_PORTLOADINGID = PORTMASTER_1.PORT_id  LEFT OUTER JOIN PORTMASTER ON ALLJOBORDERFORPE.JO_PORTDISCHARGEID = PORTMASTER.PORT_id LEFT OUTER JOIN  LEDGERS ON ALLJOBORDERFORPE.JO_LEDGERID = LEDGERS.Acc_id ON COUNTRYMASTER.country_id = ALLJOBORDERFORPE.JO_DESTINATIONID LEFT OUTER JOIN CURRENCYMASTER ON ALLJOBORDERFORPE.JO_CURRENCYID = CURRENCYMASTER.CURR_ID LEFT OUTER JOIN ITEMMASTER RIGHT OUTER JOIN ALLJOBORDERFORPE_DESC LEFT OUTER JOIN UNITMASTER ON ALLJOBORDERFORPE_DESC.JO_UNITID = UNITMASTER.unit_id ON ITEMMASTER.item_id = ALLJOBORDERFORPE_DESC.JO_QUALITYID ON ALLJOBORDERFORPE.JO_NO = ALLJOBORDERFORPE_DESC.JO_NO WHERE ALLJOBORDERFORPE_DESC.JO_CLOSED = 'TRUE' AND  ALLJOBORDERFORPE.JO_YEARID =  " & YearId & "  AND ROUND(ALLJOBORDERFORPE_DESC.JO_QTY - ALLJOBORDERFORPE_DESC.JO_READYQTY,0) > 0" & ") AS T ", " ORDER BY T.DATE, T.JONO, T.GRIDSRNO")
                End If
                LBLPE.Visible = True

            ElseIf FRMSTRING = "CLOSELAMINATION" Then
                If RBPENDING.Checked = True Then
                    dt = objclsCMST.search("*", "", "(SELECT CAST (0 AS BIT)  AS CLOSED, ISNULL(ALLJOBORDERFORLAMINATION.JO_NO, 0) AS JONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(COUNTRYMASTER.country_name, '') AS DESTINATION, ISNULL(ALLJOBORDERFORLAMINATION.JO_CIFOB, '') AS CIFFOB, ISNULL(CURRENCYMASTER.CURR_NAME, '') AS CURRENCY, ISNULL(ALLJOBORDERFORLAMINATION.JO_BANKDETAILS, '') AS BANKDETAILS, ISNULL(ALLJOBORDERFORLAMINATION.JO_REMARKS, '') AS REMARKS, ALLJOBORDERFORLAMINATION.JO_DATE AS DATE, ISNULL(ITEMMASTER.ITEM_NAME, '') AS FINISHEDQUALITY, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_GSM, '') AS GSM, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_SIZE, 0) AS SIZE, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_FOILQUALITYID, '') AS FOILQUALITY, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_FOILGSM, '') AS FOILGSM, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_PEGSM, '') AS PEGSM, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_ROLLDIEAMETER, '') AS ROLLDIAMETER, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_COREPIPEWIDTH, '') AS COREPIPEWIDTH, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_PALLETIZED, '') AS PALLETIZED, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_NARRATION, '') AS NARRATION, ROUND(ALLJOBORDERFORLAMINATION_DESC.JO_QTY - ALLJOBORDERFORLAMINATION_DESC.JO_READYQTY, 0) AS QTY, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_DESC, '') AS GRIDDESC, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(PORTMASTER.PORT_name, '') AS PORTDISCHARGE, ISNULL(PORTMASTER_1.PORT_name, '') AS PORTLOADING, ISNULL(ALLJOBORDERFORLAMINATION.JO_PROFORMANO, 0) AS PROFORMANO, ISNULL(ALLJOBORDERFORLAMINATION.TYPE, '') AS TYPE, ISNULL(SHIPTOLEDGERS.Acc_cmpname, '') AS SHIPTO FROM LEDGERS RIGHT OUTER JOIN  ALLJOBORDERFORLAMINATION LEFT OUTER JOIN LEDGERS AS SHIPTOLEDGERS ON ALLJOBORDERFORLAMINATION.JO_SHIPTOID = SHIPTOLEDGERS.Acc_id LEFT OUTER JOIN PORTMASTER AS PORTMASTER_1 ON ALLJOBORDERFORLAMINATION.JO_PORTLOADINGID = PORTMASTER_1.PORT_id LEFT OUTER JOIN  PORTMASTER ON ALLJOBORDERFORLAMINATION.JO_PORTDISCHARGEID = PORTMASTER.PORT_id ON LEDGERS.Acc_id = ALLJOBORDERFORLAMINATION.JO_LEDGERID LEFT OUTER JOIN COUNTRYMASTER ON ALLJOBORDERFORLAMINATION.JO_DESTINATIONID = COUNTRYMASTER.country_id LEFT OUTER JOIN CURRENCYMASTER ON ALLJOBORDERFORLAMINATION.JO_CURRENCYID = CURRENCYMASTER.CURR_ID LEFT OUTER JOIN ITEMMASTER RIGHT OUTER JOIN ALLJOBORDERFORLAMINATION_DESC LEFT OUTER JOIN UNITMASTER ON ALLJOBORDERFORLAMINATION_DESC.JO_UNITID = UNITMASTER.unit_id ON ITEMMASTER.item_id = ALLJOBORDERFORLAMINATION_DESC.JO_QUALITYID ON  ALLJOBORDERFORLAMINATION.JO_NO = ALLJOBORDERFORLAMINATION_DESC.JO_NO  WHERE ALLJOBORDERFORLAMINATION_DESC.JO_CLOSED = 'FALSE' AND  ALLJOBORDERFORLAMINATION.JO_YEARID = " & YearId & "  AND ROUND(ALLJOBORDERFORLAMINATION_DESC.JO_QTY - ALLJOBORDERFORLAMINATION_DESC.JO_READYQTY,0) > 0" & ") AS T", " ORDER BY T.DATE, T.JONO, T.GRIDSRNO")
                Else
                    dt = objclsCMST.search("*", "", "(SELECT CAST (0 AS BIT)  AS CLOSED, ISNULL(ALLJOBORDERFORLAMINATION.JO_NO, 0) AS JONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(COUNTRYMASTER.country_name, '') AS DESTINATION, ISNULL(ALLJOBORDERFORLAMINATION.JO_CIFOB, '') AS CIFFOB, ISNULL(CURRENCYMASTER.CURR_NAME, '') AS CURRENCY, ISNULL(ALLJOBORDERFORLAMINATION.JO_BANKDETAILS, '') AS BANKDETAILS, ISNULL(ALLJOBORDERFORLAMINATION.JO_REMARKS, '') AS REMARKS, ALLJOBORDERFORLAMINATION.JO_DATE AS DATE, ISNULL(ITEMMASTER.ITEM_NAME, '') AS FINISHEDQUALITY, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_GSM, '') AS GSM, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_SIZE, 0) AS SIZE, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_FOILQUALITYID, '') AS FOILQUALITY, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_FOILGSM, '') AS FOILGSM, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_PEGSM, '') AS PEGSM, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_ROLLDIEAMETER, '') AS ROLLDIAMETER, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_COREPIPEWIDTH, '') AS COREPIPEWIDTH, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_PALLETIZED, '') AS PALLETIZED, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_NARRATION, '') AS NARRATION, ROUND(ALLJOBORDERFORLAMINATION_DESC.JO_QTY - ALLJOBORDERFORLAMINATION_DESC.JO_READYQTY, 0) AS QTY, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(ALLJOBORDERFORLAMINATION_DESC.JO_DESC, '') AS GRIDDESC, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(PORTMASTER.PORT_name, '') AS PORTDISCHARGE, ISNULL(PORTMASTER_1.PORT_name, '') AS PORTLOADING, ISNULL(ALLJOBORDERFORLAMINATION.JO_PROFORMANO, 0) AS PROFORMANO, ISNULL(ALLJOBORDERFORLAMINATION.TYPE, '') AS TYPE, ISNULL(SHIPTOLEDGERS.Acc_cmpname, '') AS SHIPTO FROM LEDGERS RIGHT OUTER JOIN  ALLJOBORDERFORLAMINATION LEFT OUTER JOIN LEDGERS AS SHIPTOLEDGERS ON ALLJOBORDERFORLAMINATION.JO_SHIPTOID = SHIPTOLEDGERS.Acc_id LEFT OUTER JOIN PORTMASTER AS PORTMASTER_1 ON ALLJOBORDERFORLAMINATION.JO_PORTLOADINGID = PORTMASTER_1.PORT_id LEFT OUTER JOIN  PORTMASTER ON ALLJOBORDERFORLAMINATION.JO_PORTDISCHARGEID = PORTMASTER.PORT_id ON LEDGERS.Acc_id = ALLJOBORDERFORLAMINATION.JO_LEDGERID LEFT OUTER JOIN COUNTRYMASTER ON ALLJOBORDERFORLAMINATION.JO_DESTINATIONID = COUNTRYMASTER.country_id LEFT OUTER JOIN CURRENCYMASTER ON ALLJOBORDERFORLAMINATION.JO_CURRENCYID = CURRENCYMASTER.CURR_ID LEFT OUTER JOIN ITEMMASTER RIGHT OUTER JOIN ALLJOBORDERFORLAMINATION_DESC LEFT OUTER JOIN UNITMASTER ON ALLJOBORDERFORLAMINATION_DESC.JO_UNITID = UNITMASTER.unit_id ON ITEMMASTER.item_id = ALLJOBORDERFORLAMINATION_DESC.JO_QUALITYID ON  ALLJOBORDERFORLAMINATION.JO_NO = ALLJOBORDERFORLAMINATION_DESC.JO_NO   WHERE ALLJOBORDERFORLAMINATION_DESC.JO_CLOSED = 'TRUE' AND  ALLJOBORDERFORLAMINATION.JO_YEARID = " & YearId & "  AND ROUND(ALLJOBORDERFORLAMINATION_DESC.JO_QTY - ALLJOBORDERFORLAMINATION_DESC.JO_READYQTY,0) > 0" & ") AS T", " ORDER BY T.DATE, T.JONO, T.GRIDSRNO")
                End If
                LBLLAMINATION.Visible = True
            ElseIf FRMSTRING = "CLOSESLITTING" Then
                If RBPENDING.Checked = True Then
                    dt = objclsCMST.search("*", "", " (SELECT  CAST(0 AS BIT) AS CLOSED, ISNULL(COUNTRYMASTER.country_name, '') AS DESTINATION, ISNULL(CURRENCYMASTER.CURR_NAME, '') AS CURRENCY, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT,  ISNULL(SHIPTOLEDGERS.Acc_cmpname, '') AS SHIPTO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(PORTMASTER.PORT_name, '') AS PORTDISCHARGE, ISNULL(PORTLOADINGPORTMASTER.PORT_name, '')  AS PORTLOADING, ISNULL(ALLJOBORDERFORSLITTING.JO_CIFOB, '') AS CIFFOB, ISNULL(ALLJOBORDERFORSLITTING.JO_NO, 0) AS JONO, ISNULL(ALLJOBORDERFORSLITTING.JO_REMARKS, '') AS REMARKS,  ISNULL(ALLJOBORDERFORSLITTING.JO_BANKDETAILS, '') AS BANKDETAILS, ALLJOBORDERFORSLITTING.JO_SODATE AS DATE, ALLJOBORDERFORSLITTING.JO_SOTYPE AS SODATE,  ISNULL(ALLJOBORDERFORSLITTING.JO_PROFORMANO, '') AS PROFORMANO, ISNULL(ALLJOBORDERFORSLITTING.TYPE, '') AS SOTYPE, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_FOILGSM, '') AS FOILGSM,  ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_DESC, '') AS GRIDDESC, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_GSM, '') AS GSM,  ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_SIZE, '') AS SIZE, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_PEGSM, '') AS PEGSM, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_ROLLDIEAMETER, '')   AS ROLLDIAMETER, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_COREPIPEWIDTH, '') AS COREPIPEWIDTH, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_PALLETIZED, '') AS PALLETIZED,  ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_NARRATION, '') AS NARRATION, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_QTY, '') AS QTY, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_READYQTY, 0) AS READYQTY, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_FROMNO, 0) AS FROMNO, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_FROMSRNO, '') AS FROMSRNO, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_TYPE, '') AS TYPE,  ISNULL(ITEMMASTER.ITEM_NAME, '') AS FINISHEDQUALITY, ISNULL(FOILQUALITYITEMMASTER.ITEM_NAME, '') AS FOILQUALITY FROM   ITEMMASTER AS FOILQUALITYITEMMASTER RIGHT OUTER JOIN ALLJOBORDERFORSLITTING_DESC ON FOILQUALITYITEMMASTER.item_id = ALLJOBORDERFORSLITTING_DESC.JO_FOILQUALITYID LEFT OUTER JOIN ITEMMASTER ON ALLJOBORDERFORSLITTING_DESC.JO_QUALITYID = ITEMMASTER.item_id LEFT OUTER JOIN UNITMASTER ON ALLJOBORDERFORSLITTING_DESC.JO_UNITID = UNITMASTER.unit_id RIGHT OUTER JOIN  PORTMASTER AS PORTLOADINGPORTMASTER RIGHT OUTER JOIN CURRENCYMASTER RIGHT OUTER JOIN ALLJOBORDERFORSLITTING ON CURRENCYMASTER.CURR_ID = ALLJOBORDERFORSLITTING.JO_CURRENCYID ON   PORTLOADINGPORTMASTER.PORT_id = ALLJOBORDERFORSLITTING.JO_PORTLOADINGID LEFT OUTER JOIN  PORTMASTER ON ALLJOBORDERFORSLITTING.JO_PORTDISCHARGEID = PORTMASTER.PORT_id LEFT OUTER JOIN  COUNTRYMASTER ON ALLJOBORDERFORSLITTING.JO_DESTINATIONID = COUNTRYMASTER.country_id LEFT OUTER JOIN LEDGERS AS SHIPTOLEDGERS ON ALLJOBORDERFORSLITTING.JO_SHIPTOID = SHIPTOLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON ALLJOBORDERFORSLITTING.JO_LEDGERID = LEDGERS.Acc_id ON ALLJOBORDERFORSLITTING_DESC.JO_NO = ALLJOBORDERFORSLITTING.JO_NO WHERE ALLJOBORDERFORSLITTING_DESC.JO_CLOSED = 'FALSE' AND  ALLJOBORDERFORSLITTING.JO_YEARID = " & YearId & " AND ITEMMASTER.ITEM_SLITTING = 'TRUE' AND ROUND(ALLJOBORDERFORSLITTING_DESC.JO_QTY - ALLJOBORDERFORSLITTING_DESC.JO_READYQTY,0) > 0 " & ") AS T", " ORDER BY T.DATE, T.JONO, T.GRIDSRNO")
                Else
                    dt = objclsCMST.search("*", "", " (SELECT  CAST(0 AS BIT) AS CLOSED, ISNULL(COUNTRYMASTER.country_name, '') AS DESTINATION, ISNULL(CURRENCYMASTER.CURR_NAME, '') AS CURRENCY, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT,  ISNULL(SHIPTOLEDGERS.Acc_cmpname, '') AS SHIPTO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(PORTMASTER.PORT_name, '') AS PORTDISCHARGE, ISNULL(PORTLOADINGPORTMASTER.PORT_name, '')  AS PORTLOADING, ISNULL(ALLJOBORDERFORSLITTING.JO_CIFOB, '') AS CIFFOB, ISNULL(ALLJOBORDERFORSLITTING.JO_NO, 0) AS JONO, ISNULL(ALLJOBORDERFORSLITTING.JO_REMARKS, '') AS REMARKS,  ISNULL(ALLJOBORDERFORSLITTING.JO_BANKDETAILS, '') AS BANKDETAILS, ALLJOBORDERFORSLITTING.JO_SODATE AS DATE, ALLJOBORDERFORSLITTING.JO_SOTYPE AS SODATE,  ISNULL(ALLJOBORDERFORSLITTING.JO_PROFORMANO, '') AS PROFORMANO, ISNULL(ALLJOBORDERFORSLITTING.TYPE, '') AS SOTYPE, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_FOILGSM, '') AS FOILGSM,  ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_DESC, '') AS GRIDDESC, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_GSM, '') AS GSM,  ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_SIZE, '') AS SIZE, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_PEGSM, '') AS PEGSM, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_ROLLDIEAMETER, '')   AS ROLLDIAMETER, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_COREPIPEWIDTH, '') AS COREPIPEWIDTH, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_PALLETIZED, '') AS PALLETIZED,  ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_NARRATION, '') AS NARRATION, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_QTY, '') AS QTY, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_READYQTY, 0) AS READYQTY, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_FROMNO, 0) AS FROMNO, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_FROMSRNO, '') AS FROMSRNO, ISNULL(ALLJOBORDERFORSLITTING_DESC.JO_TYPE, '') AS TYPE,  ISNULL(ITEMMASTER.ITEM_NAME, '') AS FINISHEDQUALITY, ISNULL(FOILQUALITYITEMMASTER.ITEM_NAME, '') AS FOILQUALITY FROM   ITEMMASTER AS FOILQUALITYITEMMASTER RIGHT OUTER JOIN ALLJOBORDERFORSLITTING_DESC ON FOILQUALITYITEMMASTER.item_id = ALLJOBORDERFORSLITTING_DESC.JO_FOILQUALITYID LEFT OUTER JOIN ITEMMASTER ON ALLJOBORDERFORSLITTING_DESC.JO_QUALITYID = ITEMMASTER.item_id LEFT OUTER JOIN UNITMASTER ON ALLJOBORDERFORSLITTING_DESC.JO_UNITID = UNITMASTER.unit_id RIGHT OUTER JOIN  PORTMASTER AS PORTLOADINGPORTMASTER RIGHT OUTER JOIN CURRENCYMASTER RIGHT OUTER JOIN ALLJOBORDERFORSLITTING ON CURRENCYMASTER.CURR_ID = ALLJOBORDERFORSLITTING.JO_CURRENCYID ON   PORTLOADINGPORTMASTER.PORT_id = ALLJOBORDERFORSLITTING.JO_PORTLOADINGID LEFT OUTER JOIN  PORTMASTER ON ALLJOBORDERFORSLITTING.JO_PORTDISCHARGEID = PORTMASTER.PORT_id LEFT OUTER JOIN  COUNTRYMASTER ON ALLJOBORDERFORSLITTING.JO_DESTINATIONID = COUNTRYMASTER.country_id LEFT OUTER JOIN LEDGERS AS SHIPTOLEDGERS ON ALLJOBORDERFORSLITTING.JO_SHIPTOID = SHIPTOLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON ALLJOBORDERFORSLITTING.JO_LEDGERID = LEDGERS.Acc_id ON ALLJOBORDERFORSLITTING_DESC.JO_NO = ALLJOBORDERFORSLITTING.JO_NO WHERE ALLJOBORDERFORSLITTING_DESC.JO_CLOSED = 'TRUE' AND  ALLJOBORDERFORSLITTING.JO_YEARID = " & YearId & " AND ITEMMASTER.ITEM_SLITTING = 'TRUE' AND ROUND(ALLJOBORDERFORSLITTING_DESC.JO_QTY - ALLJOBORDERFORSLITTING_DESC.JO_READYQTY,0) > 0 " & ") AS T", " ORDER BY T.DATE, T.JONO, T.GRIDSRNO")
                End If
                LBLSLITTING.Visible = True
            End If
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try

            If RBENTERED.Checked = True Then
                If MsgBox("You have trying to Re-Open Closed Job Orders, Wish to Proceed?", MsgBoxStyle.YesNo) = MsgBoxResult.No Then Exit Sub
            End If

            Dim OBJCMN As New ClsCommon
            For I As Integer = 0 To gridbill.RowCount - 1
                Dim DTROW As DataRow = gridbill.GetDataRow(I)
                If FRMSTRING = "CLOSEPE" Then
                    If RBPENDING.Checked = True Then
                        If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                            If DTROW("TYPE") = "JOPE" Then Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE JOBORDERFORPE_DESC SET JO_CLOSED = 1 WHERE JO_NO = " & Val(DTROW("JONO")) & " AND JO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND JO_YEARID = " & YearId, "", "") Else Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGJOBORDERFORPE_DESC SET OJO_CLOSED = 1 WHERE OJO_NO = " & Val(DTROW("JONO")) & " AND OJO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND OJO_YEARID = " & YearId, "", "")
                        End If
                    Else
                        If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                            If DTROW("TYPE") = "JOPE" Then Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE JOBORDERFORPE_DESC SET JO_CLOSED = 0 WHERE JO_NO = " & Val(DTROW("JONO")) & " AND JO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND JO_YEARID = " & YearId, "", "") Else Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGJOBORDERFORPE_DESC SET OJO_CLOSED = 0 WHERE OJO_NO = " & Val(DTROW("JONO")) & " AND OJO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND OJO_YEARID = " & YearId, "", "")
                        End If
                    End If

                ElseIf FRMSTRING = "CLOSELAMINATION" Then
                    If RBPENDING.Checked = True Then
                        If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                            If DTROW("TYPE") = "JOLAMINATION" Then Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE JOBFORLAMINATION_DESC SET JO_CLOSED = 1 WHERE JO_NO = " & Val(DTROW("JONO")) & " AND JO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND JO_YEARID = " & YearId, "", "") Else Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGJOBFORLAMINATION_DESC SET OJO_CLOSED = 1 WHERE OJO_NO = " & Val(DTROW("JONO")) & " AND OJO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND OJO_YEARID = " & YearId, "", "")
                        End If
                    Else
                        If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                            If DTROW("TYPE") = "JOLAMINATION" Then Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE JOBFORLAMINATION_DESC SET JO_CLOSED = 0 WHERE JO_NO = " & Val(DTROW("JONO")) & " AND JO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND JO_YEARID = " & YearId, "", "") Else Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGJOBFORLAMINATION_DESC SET OJO_CLOSED = 0 WHERE OJO_NO = " & Val(DTROW("JONO")) & " AND OJO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND OJO_YEARID = " & YearId, "", "")
                        End If
                    End If

                ElseIf FRMSTRING = "CLOSESLITTING" Then
                    If RBPENDING.Checked = True Then
                        If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                            If DTROW("TYPE") = "CLOSESLITTING" Then Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE JOBFORSLITTING_DESC SET JO_CLOSED = 1 WHERE JO_NO = " & Val(DTROW("JONO")) & " AND JO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND JO_YEARID = " & YearId, "", "") Else Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGJOBFORSLITTING_DESC SET OJO_CLOSED = 1 WHERE OJO_NO = " & Val(DTROW("JONO")) & " AND OJO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND OJO_YEARID = " & YearId, "", "")
                        End If
                    Else
                        If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                            If DTROW("TYPE") = "CLOSESLITTING" Then Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE JOBFORSLITTING_DESC SET JO_CLOSED = 0 WHERE JO_NO = " & Val(DTROW("JONO")) & " AND JO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND JO_YEARID = " & YearId, "", "") Else Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGJOBFORSLITTING_DESC SET OJO_CLOSED = 0 WHERE OJO_NO = " & Val(DTROW("JONO")) & " AND OJO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND OJO_YEARID = " & YearId, "", "")
                        End If
                    End If


                End If
            Next
            MsgBox("Entries Updated")
            fillgrid("")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDREFRESH_Click(sender As Object, e As EventArgs) Handles CMDREFRESH.Click
        Try
            fillgrid("")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_RowStyle(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Grid.RowStyleEventArgs) Handles gridbill.RowStyle
        Try
            If e.RowHandle >= 0 Then
                Dim View As GridView = sender
                If View.GetRowCellDisplayText(e.RowHandle, View.Columns("CLOSED")) = "Checked" Then
                    e.Appearance.Font = New System.Drawing.Font("CALIBRI", 9.0F, System.Drawing.FontStyle.Bold)
                    e.Appearance.BackColor = Color.Yellow
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub PrintToolStripButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles PrintToolStripButton.Click
        Try

            Dim PATH As String = Application.StartupPath & "\JOB Order Short Close Details.XLS"
            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True
            opti.SheetName = "JOB Order Short Close Details"
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "JOB Order Short Close Details", gridbill.VisibleColumns.Count + gridbill.GroupCount)
        Catch ex As Exception
            MsgBox("JOB Order Short Close Details Excel File is Open, Please Close the File first then try to Export", MsgBoxStyle.Critical)
        End Try
    End Sub

    Private Sub CHKSELECTALL_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CHKSELECTALL.CheckedChanged
        Try
            If gridbilldetails.Visible = True Then
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CLOSED") = CHKSELECTALL.Checked
                Next
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_KeyDown(sender As Object, e As KeyEventArgs) Handles gridbill.KeyDown
        Try
            If e.KeyCode = Keys.Space Then
                Dim dtrow As DataRow = gridbill.GetFocusedDataRow()
                dtrow("CLOSED") = Not dtrow("CLOSED")
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

End Class