Imports BL

Public Class SelectSO
    Public PARTYNAME As String = ""
    Public FRMSTRING As String = ""
    Public DT As New DataTable
    Public WHERECLAUSE As String = ""

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub SelectMfgforPS_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Windows.Forms.Keys.Escape Then
            Me.Close()
        ElseIf e.KeyCode = Keys.Enter Then
            SendKeys.Send("{Tab}")
        End If
    End Sub

    Private Sub SelectMfgforPS_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        fillgrid("")
    End Sub

    Sub fillgrid(ByVal WHERE As String)
        Try
            Cursor.Current = Cursors.WaitCursor

            If PARTYNAME <> "" Then WHERE = WHERE & " AND ISNULL(LEDGERS.ACC_CMPNAME,'') = '" & PARTYNAME & "'"
            Dim QTYSELECT As String = ""

            If FRMSTRING = "PACKINGSLIP" Then
                Dim OBJCMN As New ClsCommon()
                Dim DT1 As DataTable = OBJCMN.SEARCH("*", "", " (SELECT CAST(0 AS BIT) AS CHK, ISNULL(ALLSALEORDER.SO_NO, 0) AS SONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(COUNTRYMASTER.country_name, '') AS DESTINATION, '' AS SPECIALREMARKS , ISNULL(ALLSALEORDER.SO_CIFFOB, '')  AS CIFFOB, ISNULL(CURRENCYMASTER.CURR_NAME, '') AS CURRENCY, ISNULL(ALLSALEORDER.SO_ORDERREFNO, '') AS ORDERREFNO, ISNULL(ALLSALEORDER.SO_PAYMENTTERM, '') AS PAYMENTTERM,  ISNULL(ALLSALEORDER.SO_BANKDETAILS, '') AS BANKDETAILS, ISNULL(ALLSALEORDER.SO_REMARKS, '') AS REMARKS, ALLSALEORDER.SO_DATE AS DATE, ISNULL(ITEMMASTER.ITEM_NAME, '') AS FINISHEDQUALITY,  ISNULL(ALLSALEORDER_DESC.SO_GSM, '') AS GSM, ISNULL(ALLSALEORDER_DESC.SO_SIZE, 0) AS SIZE, ISNULL(ALLSALEORDER_DESC.SO_SIZEDETAILS, '') AS SIZEDETAILS, ISNULL(ALLSALEORDER_DESC.SO_FOILQUALITYID, '') AS FOILQUALITY,  ISNULL(ALLSALEORDER_DESC.SO_FOILGSM, '') AS FOILGSM, ISNULL(ALLSALEORDER_DESC.SO_PEGSM, '') AS PEGSM, ISNULL(ALLSALEORDER_DESC.SO_ROLLDIAMETER, '') AS ROLLDIAMETER,  ISNULL(ALLSALEORDER_DESC.SO_COREPIPEWIDTH, '') AS COREPIPEWIDTH, ISNULL(ALLSALEORDER_DESC.SO_PALLETIZED, '') AS PALLETIZED, ISNULL(ALLSALEORDER_DESC.SO_QTY, 0) AS QTY,  ISNULL(ALLSALEORDER_DESC.SO_NARRATION, '') AS NARRATION, ISNULL(ALLSALEORDER_DESC.SO_RATE, 0) AS RATE, ISNULL(ALLSALEORDER_DESC.SO_AMOUNT, 0) AS AMOUNT,  ISNULL(ALLSALEORDER_DESC.SO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(ALLSALEORDER_DESC.SO_DESC, '') AS GRIDDESC, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(DISCHARGEPORTMASTER.PORT_name, '')  AS PORTDISCHARGE, ISNULL(LOADINGPORTMASTER.PORT_name, '') AS PORTLOADING, ISNULL(ALLSALEORDER.SO_PROFORMANO, 0) AS PROFORMANO, ISNULL(ALLSALEORDER.TYPE, '') AS TYPE,  ISNULL(SHIPTOLEDGERS.Acc_cmpname, '') AS SHIPTO, ISNULL(ALLSALEORDER_DESC.SO_GSMDETAILS, '') AS GSMDETAILS FROM ALLSALEORDER INNER JOIN ALLSALEORDER_DESC ON ALLSALEORDER.TYPE = ALLSALEORDER_DESC.TYPE AND ALLSALEORDER.SO_YEARID = ALLSALEORDER_DESC.SO_YEARID AND  ALLSALEORDER.SO_NO = ALLSALEORDER_DESC.SO_NO LEFT OUTER JOIN PORTMASTER AS LOADINGPORTMASTER ON ALLSALEORDER.SO_PORTLOADINGID = LOADINGPORTMASTER.PORT_id LEFT OUTER JOIN PORTMASTER AS DISCHARGEPORTMASTER ON ALLSALEORDER.SO_PORTDISCHARGEID = DISCHARGEPORTMASTER.PORT_id INNER JOIN LEDGERS ON ALLSALEORDER.SO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN COUNTRYMASTER ON ALLSALEORDER.SO_DESTINATIONID = COUNTRYMASTER.country_id LEFT OUTER JOIN CURRENCYMASTER ON ALLSALEORDER.SO_CURRENCYID = CURRENCYMASTER.CURR_ID LEFT OUTER JOIN UNITMASTER ON ALLSALEORDER_DESC.SO_UNITID = UNITMASTER.unit_id INNER JOIN ITEMMASTER ON ALLSALEORDER_DESC.SO_FINISHEDQUALITYID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS SHIPTOLEDGERS ON ALLSALEORDER.SO_SHIPTOID = SHIPTOLEDGERS.Acc_id WHERE  ROUND(ALLSALEORDER_DESC.SO_QTY - ALLSALEORDER_DESC.SO_OUTQTY,0) > 0 AND ALLSALEORDER_DESC.SO_CLOSED = 'FALSE' AND  ALLSALEORDER.SO_YEARID =" & YearId & WHERE & ") AS T", " ORDER BY T.DATE, T.SONO, T.GRIDSRNO")
                gridbilldetails.DataSource = DT1
                If DT1.Rows.Count > 0 Then
                    gridbill.FocusedRowHandle = gridbill.RowCount - 1
                    gridbill.TopRowIndex = gridbill.RowCount - 15
                End If
                Exit Sub

            ElseIf FRMSTRING = "MATERIALREQUIREMENT" Then
                Dim OBJCMN As New ClsCommon()
                Dim DT1 As DataTable = OBJCMN.SEARCH(" CAST(0 AS BIT) AS CHK,  ISNULL(ALLSALEORDER_DESC.SO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(SHIPTOLEDGERS.Acc_cmpname, '') AS SHIPTO, ISNULL(ALLSALEORDER.SO_NO, 0) AS SONO,  ALLSALEORDER.SO_DATE AS DATE, ISNULL(FINISHEDITEMMASTER.ITEM_NAME, '') AS FINISHEDQUALITY, ISNULL(PORTDISCHARGE.PORT_name, '') AS PORTDISCHARGE, ISNULL(PORTLOADING.PORT_name, '')  AS PORTLOADING, ISNULL(ALLSALEORDER_DESC.SO_QTY, 0) AS QTY, ISNULL(ALLSALEORDER_DESC.SO_RATE, 0) AS RATE, ISNULL(ALLSALEORDER_DESC.SO_AMOUNT, 0) AS AMOUNT, ISNULL(ALLSALEORDER.SO_PROFORMANO, 0) AS PROFORMANO, ISNULL(COUNTRYMASTER.country_name, '') AS DESTINATION, ISNULL(ALLSALEORDER.SO_CIFFOB, '') AS CIFFOB,  ISNULL(CURRENCYMASTER.CURR_NAME, '') AS CURRENCY, ISNULL(ALLSALEORDER.SO_ORDERREFNO, '') AS ORDERREFNO, ISNULL(ALLSALEORDER.SO_PAYMENTTERM, '') AS PAYMENTTERM,  ISNULL(ALLSALEORDER.SO_BANKDETAILS, '') AS BANKDETAILS, ISNULL(ALLSALEORDER.SO_REMARKS, '') AS REMARKS, ISNULL(ALLSALEORDER_DESC.SO_GSM, 0) AS GSM, ISNULL(ALLSALEORDER_DESC.SO_GSMDETAILS, '') AS GSMDETAILS,ISNULL(ALLSALEORDER_DESC.SO_SIZE, 0)  AS SIZE,ISNULL(ALLSALEORDER_DESC.SO_SIZEDETAILS, '') AS SIZEDETAILS, ISNULL(FOILQUALITY.ITEM_NAME, '') AS FOILQUALITY, ISNULL(ALLSALEORDER_DESC.SO_FOILGSM, 0) AS FOILGSM, ISNULL(ALLSALEORDER_DESC.SO_PEGSM, 0) AS PEGSM,  ISNULL(ALLSALEORDER_DESC.SO_ROLLDIAMETER, '') AS ROLLDIAMETER, ISNULL(ALLSALEORDER_DESC.SO_COREPIPEWIDTH, '') AS COREPIPEWIDTH, ISNULL(ALLSALEORDER_DESC.SO_PALLETIZED, '') AS PALLETIZED,  ISNULL(ALLSALEORDER_DESC.SO_NARRATION, '') AS NARRATION, ALLSALEORDER_DESC.TYPE, ISNULL(ALLSALEORDER_DESC.SO_DESC, '') AS GRIDDESC, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT ,ISNULL(ALLSALEORDER.SO_SPECIALREMARKS,'')	AS SPECIALREMARKS  ", "", " ALLSALEORDER INNER JOIN ALLSALEORDER_DESC ON ALLSALEORDER.SO_NO = ALLSALEORDER_DESC.SO_NO AND ALLSALEORDER.SO_YEARID = ALLSALEORDER_DESC.SO_YEARID AND ALLSALEORDER.TYPE = ALLSALEORDER_DESC.TYPE LEFT OUTER JOIN UNITMASTER ON ALLSALEORDER_DESC.SO_UNITID = UNITMASTER.unit_id LEFT OUTER JOIN ITEMMASTER AS FOILQUALITY ON ALLSALEORDER_DESC.SO_FOILQUALITYID = FOILQUALITY.item_id LEFT OUTER JOIN CURRENCYMASTER ON ALLSALEORDER.SO_CURRENCYID = CURRENCYMASTER.CURR_ID LEFT OUTER JOIN COUNTRYMASTER ON ALLSALEORDER.SO_DESTINATIONID = COUNTRYMASTER.country_id LEFT OUTER JOIN PORTMASTER AS PORTLOADING ON ALLSALEORDER.SO_PORTLOADINGID = PORTLOADING.PORT_id LEFT OUTER JOIN LEDGERS AS SHIPTOLEDGERS ON ALLSALEORDER.SO_SHIPTOID = SHIPTOLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON ALLSALEORDER.SO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN ITEMMASTER AS FINISHEDITEMMASTER ON ALLSALEORDER_DESC.SO_FINISHEDQUALITYID = FINISHEDITEMMASTER.item_id LEFT OUTER JOIN PORTMASTER AS PORTDISCHARGE ON ALLSALEORDER.SO_PORTDISCHARGEID = PORTDISCHARGE.PORT_id ", " AND ALLSALEORDER_DESC.SO_REQDONE = 'FALSE' AND ALLSALEORDER_DESC.SO_CLOSED = 'FALSE' AND ROUND(ALLSALEORDER_DESC.SO_QTY - ALLSALEORDER_DESC.SO_OUTQTY,0) > 0 AND ALLSALEORDER.SO_YEARID =" & YearId & "   ORDER BY ALLSALEORDER.SO_NO, ALLSALEORDER_DESC.SO_GRIDSRNO ")
                gridbilldetails.DataSource = DT1
                If DT1.Rows.Count > 0 Then
                    gridbill.FocusedRowHandle = gridbill.RowCount - 1
                    gridbill.TopRowIndex = gridbill.RowCount - 15
                End If
                Exit Sub

            ElseIf FRMSTRING = "SOPE" Then
                WHERE = WHERE & " AND ITEMMASTER.ITEM_PE = 'TRUE' AND ROUND(ALLSALEORDER_DESC.SO_QTY - ALLSALEORDER_DESC.SO_JOQTYPE,0) > 0"
                QTYSELECT = " ROUND(ALLSALEORDER_DESC.SO_QTY - ALLSALEORDER_DESC.SO_JOQTYPE,0)"

            ElseIf FRMSTRING = "SOLAMINATION" Then
                WHERE = WHERE & " AND ITEMMASTER.ITEM_LAMINATION = 'TRUE' AND ROUND(ALLSALEORDER_DESC.SO_QTY - ALLSALEORDER_DESC.SO_JOQTYLAMINATION,0) > 0"
                QTYSELECT = " ROUND(ALLSALEORDER_DESC.SO_QTY - ALLSALEORDER_DESC.SO_JOQTYLAMINATION,0)"

            ElseIf FRMSTRING = "SOSLITTING" Then
                WHERE = WHERE & " AND ITEMMASTER.ITEM_SLITTING = 'TRUE' AND ROUND(ALLSALEORDER_DESC.SO_QTY - ALLSALEORDER_DESC.SO_JOQTYSLITTING,0) > 0"
                QTYSELECT = " ROUND(ALLSALEORDER_DESC.SO_QTY - ALLSALEORDER_DESC.SO_JOQTYSLITTING,0)"


            End If

            Dim objclspreq As New ClsCommon()
            Dim DT As DataTable = objclspreq.SEARCH("*", "", " (SELECT  CAST(0 AS BIT) AS CHK, ISNULL(ALLSALEORDER.SO_NO, 0) AS SONO, ISNULL(ALLSALEORDER.SO_WASTAGEPER, 0) AS WASTAGEPER , ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(COUNTRYMASTER.country_name, '') AS DESTINATION, ISNULL(ALLSALEORDER.SO_CIFFOB, '') AS CIFFOB, ISNULL(CURRENCYMASTER.CURR_NAME, '') AS CURRENCY, ISNULL(ALLSALEORDER_DESC.SO_GSMDETAILS, '') AS GSMDETAILS, ISNULL(ALLSALEORDER.SO_ORDERREFNO, '') AS ORDERREFNO, ISNULL(ALLSALEORDER.SO_PAYMENTTERM, '') AS PAYMENTTERM, ISNULL(ALLSALEORDER.SO_BANKDETAILS, '') AS BANKDETAILS, ISNULL(ALLSALEORDER.SO_REMARKS, '') AS REMARKS, ALLSALEORDER.SO_DATE AS DATE, ISNULL(ITEMMASTER.ITEM_NAME, '') AS FINISHEDQUALITY, ISNULL(ALLSALEORDER_DESC.SO_GSM, '') AS GSM,  ISNULL(ALLSALEORDER_DESC.SO_MOTHERSIZE, '') AS MOTHERSIZE, ISNULL(ALLSALEORDER_DESC.SO_SIZE, 0) AS SIZE, ISNULL(ALLSALEORDER_DESC.SO_SIZEDETAILS, '') AS SIZEDETAILS, ISNULL(ALLSALEORDER_DESC.SO_FOILQUALITYID, '') AS FOILQUALITY, ISNULL(ALLSALEORDER_DESC.SO_FOILGSM, '') AS FOILGSM, ISNULL(ALLSALEORDER_DESC.SO_PEGSM, '') AS PEGSM, ISNULL(ALLSALEORDER_DESC.SO_ROLLDIAMETER, '') AS ROLLDIAMETER, ISNULL(ALLSALEORDER_DESC.SO_COREPIPEWIDTH, '') AS COREPIPEWIDTH, ISNULL(ALLSALEORDER_DESC.SO_PALLETIZED, '') AS PALLETIZED, ISNULL(ALLSALEORDER_DESC.SO_NARRATION, '') AS NARRATION," & QTYSELECT & " AS QTY,ISNULL(ALLSALEORDER_DESC.SO_RATE, 0) AS RATE, ISNULL(ALLSALEORDER_DESC.SO_AMOUNT, 0) AS AMOUNT, ISNULL(ALLSALEORDER_DESC.SO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(ALLSALEORDER_DESC.SO_DESC, '') AS GRIDDESC, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(DISCHARGEPORTMASTER.PORT_name, '') AS PORTDISCHARGE, ISNULL(LOADINGPORTMASTER.PORT_name, '') AS PORTLOADING, ISNULL(ALLSALEORDER.SO_PROFORMANO, 0) AS PROFORMANO, ISNULL(ALLSALEORDER.TYPE, '') AS TYPE, ISNULL(SHIPTOLEDGERS.Acc_cmpname, '') AS SHIPTO FROM ALLSALEORDER INNER JOIN ALLSALEORDER_DESC ON ALLSALEORDER.TYPE = ALLSALEORDER_DESC.TYPE AND ALLSALEORDER.SO_YEARID = ALLSALEORDER_DESC.SO_YEARID AND ALLSALEORDER.SO_NO = ALLSALEORDER_DESC.SO_NO LEFT OUTER JOIN PORTMASTER AS LOADINGPORTMASTER ON ALLSALEORDER.SO_PORTLOADINGID = LOADINGPORTMASTER.PORT_id LEFT OUTER JOIN PORTMASTER AS DISCHARGEPORTMASTER ON ALLSALEORDER.SO_PORTDISCHARGEID = DISCHARGEPORTMASTER.PORT_id INNER JOIN LEDGERS ON ALLSALEORDER.SO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN COUNTRYMASTER ON ALLSALEORDER.SO_DESTINATIONID = COUNTRYMASTER.country_id LEFT OUTER JOIN CURRENCYMASTER ON ALLSALEORDER.SO_CURRENCYID = CURRENCYMASTER.CURR_ID LEFT OUTER JOIN UNITMASTER ON ALLSALEORDER_DESC.SO_UNITID = UNITMASTER.unit_id INNER JOIN ITEMMASTER ON ALLSALEORDER_DESC.SO_FINISHEDQUALITYID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS SHIPTOLEDGERS ON ALLSALEORDER.SO_SHIPTOID = SHIPTOLEDGERS.Acc_id WHERE ALLSALEORDER_DESC.SO_CLOSED = 'FALSE' AND  ALLSALEORDER.SO_YEARID =" & YearId & WHERE & ") AS T", " ORDER BY T.DATE, T.SONO, T.GRIDSRNO")
            gridbilldetails.DataSource = DT

            If DT.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If

        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        Finally
            Cursor.Current = Cursors.Default
        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try
            If FRMSTRING = "MATERIALREQUIREMENT" Or FRMSTRING = "PACKINGSLIP" Then

                DT.Columns.Add("DATE")
                DT.Columns.Add("NAME")
                DT.Columns.Add("FINISHEDQUALITY")
                DT.Columns.Add("PORTDISCHARGE")
                DT.Columns.Add("PORTLOADING")
                DT.Columns.Add("QTY")
                DT.Columns.Add("RATE")
                DT.Columns.Add("AMOUNT")
                DT.Columns.Add("PROFORMANO")
                DT.Columns.Add("DESTINATION")
                DT.Columns.Add("CIFFOB")
                DT.Columns.Add("CURRENCY")
                DT.Columns.Add("SHIPTO")
                DT.Columns.Add("ORDERREFNO")
                DT.Columns.Add("PAYMENTTERM")
                DT.Columns.Add("BANKDETAILS")
                DT.Columns.Add("REMARKS")
                DT.Columns.Add("GSM")
                DT.Columns.Add("GSMDETAILS")
                DT.Columns.Add("SIZE")

                DT.Columns.Add("FOILQUALITY")
                DT.Columns.Add("FOILGSM")
                DT.Columns.Add("PEGSM")
                DT.Columns.Add("ROLLDIAMETER")
                DT.Columns.Add("COREPIPEWIDTH")
                DT.Columns.Add("PALLETIZED")
                DT.Columns.Add("NARRATION")
                DT.Columns.Add("SONO")
                DT.Columns.Add("GRIDSRNO")
                DT.Columns.Add("TYPE")
                DT.Columns.Add("GRIDDESC")
                DT.Columns.Add("UNIT")
                DT.Columns.Add("SPECIALREMARKS")


                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    If Convert.ToBoolean(dtrow("CHK")) = True Then
                        DT.Rows.Add(dtrow("DATE"), dtrow("NAME"), dtrow("FINISHEDQUALITY"), dtrow("PORTDISCHARGE"), dtrow("PORTLOADING"), Val(dtrow("QTY")), Val(dtrow("RATE")), Val(dtrow("AMOUNT")), dtrow("PROFORMANO"), dtrow("DESTINATION"), dtrow("CIFFOB"), dtrow("CURRENCY"), dtrow("SHIPTO"), dtrow("ORDERREFNO"), dtrow("PAYMENTTERM"), dtrow("BANKDETAILS"), dtrow("REMARKS"), dtrow("GSM"), dtrow("GSMDETAILS"), Val(dtrow("SIZE")), dtrow("FOILQUALITY"), dtrow("FOILGSM"), dtrow("PEGSM"), dtrow("ROLLDIAMETER"), dtrow("COREPIPEWIDTH"), dtrow("PALLETIZED"), dtrow("NARRATION"), Val(dtrow("SONO")), Val(dtrow("GRIDSRNO")), dtrow("TYPE"), dtrow("GRIDDESC"), dtrow("UNIT"), dtrow("SPECIALREMARKS"))
                        Me.Close()
                        ' Exit Sub
                    End If
                Next
                Me.Close()
            Else

                DT.Columns.Add("DATE")
                DT.Columns.Add("NAME")
                DT.Columns.Add("FINISHEDQUALITY")
                DT.Columns.Add("PORTDISCHARGE")
                DT.Columns.Add("PORTLOADING")
                DT.Columns.Add("QTY")
                DT.Columns.Add("RATE")
                DT.Columns.Add("AMOUNT")
                DT.Columns.Add("PROFORMANO")
                DT.Columns.Add("DESTINATION")
                DT.Columns.Add("CIFFOB")
                DT.Columns.Add("CURRENCY")
                DT.Columns.Add("SHIPTO")
                DT.Columns.Add("ORDERREFNO")
                DT.Columns.Add("PAYMENTTERM")
                DT.Columns.Add("BANKDETAILS")
                DT.Columns.Add("REMARKS")
                DT.Columns.Add("GSM")
                DT.Columns.Add("GSMDETAILS")
                DT.Columns.Add("MOTHERSIZE")

                DT.Columns.Add("SIZE")
                DT.Columns.Add("SIZEDETAILS")
                DT.Columns.Add("FOILQUALITY")
                DT.Columns.Add("FOILGSM")
                DT.Columns.Add("PEGSM")
                DT.Columns.Add("ROLLDIAMETER")
                DT.Columns.Add("COREPIPEWIDTH")
                DT.Columns.Add("PALLETIZED")
                DT.Columns.Add("NARRATION")
                DT.Columns.Add("SONO")
                DT.Columns.Add("GRIDSRNO")
                DT.Columns.Add("TYPE")
                DT.Columns.Add("GRIDDESC")
                DT.Columns.Add("UNIT")
                DT.Columns.Add("WASTAGEPER")


                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    If Convert.ToBoolean(dtrow("CHK")) = True Then
                        DT.Rows.Add(dtrow("DATE"), dtrow("NAME"), dtrow("FINISHEDQUALITY"), dtrow("PORTDISCHARGE"), dtrow("PORTLOADING"), Val(dtrow("QTY")), Val(dtrow("RATE")), Val(dtrow("AMOUNT")), dtrow("PROFORMANO"), dtrow("DESTINATION"), dtrow("CIFFOB"), dtrow("CURRENCY"), dtrow("SHIPTO"), dtrow("ORDERREFNO"), dtrow("PAYMENTTERM"), dtrow("BANKDETAILS"), dtrow("REMARKS"), dtrow("GSM"), dtrow("GSMDETAILS"), dtrow("MOTHERSIZE"), Val(dtrow("SIZE")), dtrow("SIZEDETAILS"), dtrow("FOILQUALITY"), dtrow("FOILGSM"), dtrow("PEGSM"), dtrow("ROLLDIAMETER"), dtrow("COREPIPEWIDTH"), dtrow("PALLETIZED"), dtrow("NARRATION"), Val(dtrow("SONO")), Val(dtrow("GRIDSRNO")), dtrow("TYPE"), dtrow("GRIDDESC"), dtrow("UNIT"), dtrow("WASTAGEPER"))
                        Me.Close()
                        Exit Sub
                    End If
                Next
                Me.Close()
            End If


        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub CHKSELECTALL_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CHKSELECTALL.CheckedChanged
        Try
            If gridbilldetails.Visible = True Then
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CHK") = CHKSELECTALL.Checked
                Next
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class