
Imports BL

Public Class SelectProformaForPO

    Public FRMSTRING As String = ""
    Public PARTYNAME As String = ""
    Public DT As New DataTable


    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub SelectProformaForPO_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Windows.Forms.Keys.Escape Then
            Me.Close()
        ElseIf e.KeyCode = Keys.Enter Then
            SendKeys.Send("{Tab}")
        End If
    End Sub

    Private Sub SelectProformaForPO_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        fillgrid()
    End Sub

    Sub fillgrid(Optional ByVal where As String = "")
        Try
            Cursor.Current = Cursors.WaitCursor
            If PARTYNAME <> "" Then where = where & " AND LEDGERS.Acc_cmpname='" & PARTYNAME & "'"
            Dim OBJCMN As New ClsCommon()
            Dim DT As New DataTable
            If FRMSTRING = "PO" Then
                DT = OBJCMN.SEARCH(" ALLPROFORMAINVOICEMASTER.INVOICE_NO AS PROFORMANO, ALLPROFORMAINVOICEMASTER.INVOICE_TYPE AS TYPE, ALLPROFORMAINVOICEMASTER.INVOICE_DATE AS DATE, LEDGERS.Acc_cmpname AS NAME, ALLPROFORMAINVOICEMASTER.INVOICE_ORDERREFNO AS ORDERREFNO, ALLPROFORMAINVOICEMASTER.INVOICE_PAYMENTTERM AS PAYMENTTERMS, ALLPROFORMAINVOICEMASTER.INVOICE_REMARKS AS REMARKS, ITEMMASTER.ITEM_NAME AS ITEMNAME, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_GSM AS GSM, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_GSMDETAILS AS GSMDETAILS, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_SIZE AS SIZE, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_SIZEDETAILS AS SIZEDETAILS, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_QTY AS QTY, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_RATE AS RATE , ISNULL(ALLPROFORMAINVOICEMASTER_DESC.INVOICE_GRIDSRNO,0) AS GRIDSRNO ", "", " ALLPROFORMAINVOICEMASTER INNER JOIN ALLPROFORMAINVOICEMASTER_DESC ON ALLPROFORMAINVOICEMASTER.INVOICE_NO = ALLPROFORMAINVOICEMASTER_DESC.INVOICE_NO AND ALLPROFORMAINVOICEMASTER.INVOICE_YEARID = ALLPROFORMAINVOICEMASTER_DESC.INVOICE_YEARID AND ALLPROFORMAINVOICEMASTER.INVOICE_TYPE = ALLPROFORMAINVOICEMASTER_DESC.INVOICE_TYPE INNER JOIN ITEMMASTER ON ALLPROFORMAINVOICEMASTER_DESC.INVOICE_FINISHEDQUALITYID = ITEMMASTER.item_id INNER JOIN LEDGERS ON ALLPROFORMAINVOICEMASTER.INVOICE_LEDGERID = LEDGERS.Acc_id", " AND ALLPROFORMAINVOICEMASTER_DESC.INVOICE_CLOSED = 'FALSE' AND ALLPROFORMAINVOICEMASTER_DESC.INVOICE_PODONE = 'FALSE' AND ALLPROFORMAINVOICEMASTER.INVOICE_YEARID = " & YearId & where & " ORDER BY ALLPROFORMAINVOICEMASTER.INVOICE_NO, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_GRIDSRNO")
            ElseIf FRMSTRING = "SO" Then
                DT = OBJCMN.SEARCH(" ALLPROFORMAINVOICEMASTER.INVOICE_NO AS PROFORMANO, ALLPROFORMAINVOICEMASTER.INVOICE_TYPE AS TYPE, ALLPROFORMAINVOICEMASTER.INVOICE_DATE AS DATE, LEDGERS.Acc_cmpname AS NAME,  ALLPROFORMAINVOICEMASTER.INVOICE_ORDERREFNO AS ORDERREFNO, ALLPROFORMAINVOICEMASTER.INVOICE_PAYMENTTERM AS PAYMENTTERMS, ALLPROFORMAINVOICEMASTER.INVOICE_REMARKS AS REMARKS, ITEMMASTER.ITEM_NAME AS ITEMNAME, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_GSM AS GSM,ALLPROFORMAINVOICEMASTER_DESC.INVOICE_GSMDETAILS AS GSMDETAILS, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_SIZE AS SIZE, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_SIZEDETAILS AS SIZEDETAILS, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_QTY AS QTY, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_RATE AS RATE, SHIPTOLEDGERS.Acc_cmpname AS SHIPTO, PORTMASTERDISCHARGE.PORT_name AS PORTDISCHARGE, PORTMASTER.PORT_name AS PORTLOADING, ALLPROFORMAINVOICEMASTER.INVOICE_CIFFOB AS CIFFOB, COUNTRYMASTER_1.country_name AS DESTINATION, ALLPROFORMAINVOICEMASTER.INVOICE_BANKDETAILS AS BANKDETAILS, CURRENCYMASTER.CURR_NAME AS CURRENCY ", "", "    ITEMMASTER RIGHT OUTER JOIN CURRENCYMASTER RIGHT OUTER JOIN ALLPROFORMAINVOICEMASTER INNER JOIN ALLPROFORMAINVOICEMASTER_DESC ON ALLPROFORMAINVOICEMASTER.INVOICE_NO = ALLPROFORMAINVOICEMASTER_DESC.INVOICE_NO AND ALLPROFORMAINVOICEMASTER.INVOICE_YEARID = ALLPROFORMAINVOICEMASTER_DESC.INVOICE_YEARID AND ALLPROFORMAINVOICEMASTER.INVOICE_TYPE = ALLPROFORMAINVOICEMASTER_DESC.INVOICE_TYPE ON CURRENCYMASTER.CURR_ID = ALLPROFORMAINVOICEMASTER.INVOICE_CURRENCYID LEFT OUTER JOIN COUNTRYMASTER AS COUNTRYMASTER_1 ON ALLPROFORMAINVOICEMASTER.INVOICE_DESTINATIONID = COUNTRYMASTER_1.country_id LEFT OUTER JOIN LEDGERS ON ALLPROFORMAINVOICEMASTER.INVOICE_LEDGERID = LEDGERS.Acc_id ON ITEMMASTER.item_id = ALLPROFORMAINVOICEMASTER_DESC.INVOICE_FINISHEDQUALITYID LEFT OUTER JOIN PORTMASTER ON ALLPROFORMAINVOICEMASTER.INVOICE_PORTLOADINGID = PORTMASTER.PORT_id LEFT OUTER JOIN PORTMASTER AS PORTMASTERDISCHARGE ON ALLPROFORMAINVOICEMASTER.INVOICE_PORTDISCHARGEID = PORTMASTERDISCHARGE.PORT_id LEFT OUTER JOIN LEDGERS AS SHIPTOLEDGERS ON ALLPROFORMAINVOICEMASTER.INVOICE_SHIPTOID = SHIPTOLEDGERS.Acc_id ", " AND ALLPROFORMAINVOICEMASTER_DESC.INVOICE_CLOSED = 'FALSE' AND ALLPROFORMAINVOICEMASTER_DESC.INVOICE_SODONE = 'FALSE' AND ALLPROFORMAINVOICEMASTER.INVOICE_YEARID = " & YearId & where & " ORDER BY ALLPROFORMAINVOICEMASTER.INVOICE_NO, ALLPROFORMAINVOICEMASTER_DESC.INVOICE_GRIDSRNO")
            End If
            gridbilldetails.DataSource = DT
            If DT.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        Finally
            Cursor.Current = Cursors.Default

        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try
            If FRMSTRING = "SO" Then

                DT.Columns.Add("PROFORMANO")
                DT.Columns.Add("TYPE")
                DT.Columns.Add("DATE")
                DT.Columns.Add("NAME")
                DT.Columns.Add("ORDERREFNO")
                DT.Columns.Add("PAYMENTTERMS")
                DT.Columns.Add("REMARKS")
                DT.Columns.Add("ITEMNAME")
                DT.Columns.Add("GSM")
                DT.Columns.Add("GSMDETAILS")
                DT.Columns.Add("SIZE")
                DT.Columns.Add("SIZEDETAILS")
                DT.Columns.Add("QTY")
                DT.Columns.Add("RATE")
                DT.Columns.Add("SHIPTO")
                DT.Columns.Add("PORTDISCHARGE")
                DT.Columns.Add("PORTLOADING")
                DT.Columns.Add("CIFFOB")
                DT.Columns.Add("DESTINATION")
                DT.Columns.Add("BANKDETAILS")
                DT.Columns.Add("CURRENCY")



                Dim SELECTEDROWS As Int32() = gridbill.GetSelectedRows()
                For I As Integer = 0 To Val(SELECTEDROWS.Length - 1)
                    Dim dtrow As DataRow = gridbill.GetDataRow(SELECTEDROWS(I))
                    DT.Rows.Add(dtrow("PROFORMANO"), dtrow("TYPE"), dtrow("DATE"), dtrow("NAME"), dtrow("ORDERREFNO"), dtrow("PAYMENTTERMS"), dtrow("REMARKS"), dtrow("ITEMNAME"), dtrow("GSM"), dtrow("GSMDETAILS"), dtrow("SIZE"), dtrow("SIZEDETAILS"), Val(dtrow("QTY")), Val(dtrow("RATE")), dtrow("SHIPTO"), dtrow("PORTDISCHARGE"), dtrow("PORTLOADING"), dtrow("CIFFOB"), dtrow("DESTINATION"), dtrow("BANKDETAILS"), dtrow("CURRENCY"))
                Next
                Me.Close()
            Else
                DT.Columns.Add("PROFORMANO")
                DT.Columns.Add("TYPE")
                DT.Columns.Add("DATE")
                DT.Columns.Add("NAME")
                DT.Columns.Add("ORDERREFNO")
                DT.Columns.Add("PAYMENTTERMS")
                DT.Columns.Add("REMARKS")
                DT.Columns.Add("ITEMNAME")
                DT.Columns.Add("GSM")
                DT.Columns.Add("GSMDETAILS")
                DT.Columns.Add("SIZE")
                DT.Columns.Add("SIZEDETAILS")
                DT.Columns.Add("QTY")
                DT.Columns.Add("RATE")
                DT.Columns.Add("GRIDSRNO")
                Dim SELECTEDROWS As Int32() = gridbill.GetSelectedRows()
                For I As Integer = 0 To Val(SELECTEDROWS.Length - 1)
                    Dim dtrow As DataRow = gridbill.GetDataRow(SELECTEDROWS(I))
                    DT.Rows.Add(dtrow("PROFORMANO"), dtrow("TYPE"), dtrow("DATE"), dtrow("NAME"), dtrow("ORDERREFNO"), dtrow("PAYMENTTERMS"), dtrow("REMARKS"), dtrow("ITEMNAME"), dtrow("GSM"), dtrow("GSMDETAILS"), dtrow("SIZE"), dtrow("SIZEDETAILS"), Val(dtrow("QTY")), Val(dtrow("RATE")), Val(dtrow("GRIDSRNO")))
                Next
                Me.Close()
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

End Class